### ISSUE TITLE
I cant get anything

### ISSUE THREAD

**Issue by rifat-h** [maateen/mama#2]
I am on ubuntu 16.04. after opening "mama" when i say something like youtube or time. after a lil while i get error messege "Access denied".

**Comment by rifat-h** [comment]
rifat@his-own-pc:/usr/share/mama$ python3 mama.py
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
sh: 1: play: not found
* recording
* done recording

(process:11905): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:2635: instance '0x14578a0' has no handler with id '6'
Error dialog closed

**Comment by maateen** [comment]
As I didn't find any user-base of this app, then I started to discontinue the project. So, I unsubscribed the Bing API. That's the reason you're getting the issue.

Use the source code to build one for you.

**Comment by joymia** [comment]
Did, your friend in avro linux project still writing avro in go language ?
